
env:
	server:
		scripts:
			
			# alias is taken from filename for `include.use(ALIAS)`
			# so it same as, e.g '../Utils/Utils.js::Utils'
			
			- '../Utils/Utils.js'
			- '../Model/Model.js'
			- '../Queue/Queue.js'