services:
  mongodb

before_script:
  - cd Utils
  - npm install
  - cd ../Api
  - npm install
  - cd ..
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 4
  - node_modules/.bin/atma server &
  - sleep 4
  - firefox http://localhost:5777/utest/ &
  - sleep 4
 
script:
  - "npm test"
 
language: node_js