env:
	both:

		routes:
			atma_compo: '/.reference/atma/compos/{0}/lib/{1}.js'
			
			public : '/public/script/{0}.js'
			public_compo: '/public/compo/{0}/{1}.es6'
			public_control: '/public/control/{0}/{1}.es6'
			view: '/public/view/{0}/{1}.es6'

		scripts:
			bower:
				- es6-shim
				- atma-formatter
				- atma-i18n
				- compo-tabs
				- compo-typeahead
				- compo-ace
			
			public_control:
				- markdown
				- infoPane
				- bootstrap
				- bootstrap/tooltip
				
			public_compo:
				- app
				- menu
				- list
				- view/viewManager
				- elements
				- resolver