env:
	both:

		include:
			cfg:
				loader:


		routes:
			atma: '/.reference/atma/{0}/lib/{1}.js'
			atma_compo: '/.reference/atma/compos/{0}/lib/{1}.js'
			
			public : '/public/script/{0}.js'
			public_compo: '/public/compo/{0}/{1}.es6'
			view: '/public/view/{0}/{1}.es6'

		scripts:
			atma:
				- util-format/format
				- i18n/localization
			public_compo:
				- menu
				- view/viewManager
			