env:
	both:

		routes:
			atma_compo: '/.reference/atma/compos/{0}/lib/{1}.js'
			
			public : '/public/script/{0}.js'
			public_compo: '/public/compo/{0}/{1}.es6'
			view: '/public/view/{0}/{1}.es6'

		scripts:
			bower:
				- atma-formatter
				- atma-i18n
				
			public_compo:
				- app
				- menu
				- list
				- view/viewManager