

env:
	client:

		include:
			src: '/.reference/atma/include/lib/include.js'
		
		routes:
			control: '/public/control/{0}/{1}.es6'
			
		scripts:
			atma:
				- ruqq/dom/jquery
				- class
				- mask
				- '#if debug':
					- mask/plugin.reload

				- mask-node/mask.bootstrap
				- ruta
				- mask-animation/mask.animation
				- '#if debug':
					- include/include.autoreload
			
			atma_compo:
				- prism
				- tabs
			control:
				- ajax-loader
			
		styles:
			- '/.reference/bootstrap/dist/css/bootstrap.css'
		
