

env:
	client:

		include:
			src: '/bower_components/includejs/lib/include.js'
		
		routes:
			project: '/.reference/{0}/{0}.js?type=client'
			control: '/public/control/{0}/{1}.es6'
			style: '/public/style/{0}.less'
		scripts:
			bower:
				- jquery
				- atma-class
				- maskjs
				- '#if debug':
					- maskjs/lib/plugin.reload.js

				- maskjs/lib/mask.bootstrap.js
				- ruta
				- atma-logger
				- mask-animation
				- '#if debug':
					- includejs/lib/include.autoreload.js
				- bootstrap
			
			project:
				- Utils
				- Model
				
			atma_compo:
				#- prism
				#- tabs
				
			control:
				- ajax-loader
				- timer
				- dialog
				- pageActivity
			
			public_compo:
				
		styles:
			bower:
				- bootstrap
				- fontawesome
			
			application:
				- '/public/style/main.less'
				- '/public/style/layout.less'

			
