
env:
	server:


		routes:
			server : '/server/{0}.es6' 
			server_lib : '/server/lib/{0}.es6' 
			server_compo : '/server/compo/{0}/{1}.es6'

			Project: '../{0}/{0}.js'
			Release: '../{0}/{0}.min.js'
		scripts:
			
			Project:
				# filename is taken from the resource alias (for `include.use(ALIAS)`)
				# so it the same as, e.g 'Utils::Utils'
				
				- 'Utils'
				- 'Model'
				- 'Queue'
				- 'Worker'
			
			#Release:
			#	'#if release':
			#		- 'Worker'
			
			
