
service:
	location: '/src/service/{0}.es6'
services:
	'^/task':
		controller: Task
	'^/tasks':
		controller: Tasks
	'^/workers':
		controller: Workers
	'^/system':
		controller: System
	'^/app':
		controller: Application
	'^/apps':
		controller: Applications
