port:
	'#if ENV=="test"': 5887
	'default': 5888

hasWorker: false
	
mongo:
	db:
		'#if ENV=="test"': test-task-scheduler
		'default': task-scheduler
	
subapps:
	rest:
		# all requests to `/rest/***` are piped to Api Application
		controller: /../Api/index.js
