
# start queue application with one worker
# otherwise extern workers should be started

embedWorker:
	'#if (debug || test)': true
	'default': false
	
subapps:
	rest:
		# all requests to `/rest/***` are piped to Api Application
		controller: /../Api/Api.js
	
i18n:
	support:
		- en
		- de
	path: '~/public/localization/%%.json'
	
static: '/App/'