

page:
	route: '/?:page/?:tab/?:section'
	
	
	location:
		controller: '/server/http/page/{0}/{1}.js'
		template: '/server/http/page/{0}/{1}.mask'
		master: '/server/http/master/{0}.mask'
		viewTemplate: '/public/view/{0}/{1}.mask'
		viewController: '/public/view/{0}/{1}.js'
		viewStyle: '/public/view/{0}/{1}.less'
	
	extension:
		javascript: js
		style: less
		template: mask
	
	index:
		template: index
		master: default
	
pages:
	# Page urls
	# Default page path is /server/http/page/index/index.mask
	# Each page item also has some additional infos
	# - title - Page Title

