page:
	route: '/?:page/?:tab/?:section'
		
	location:
		template: '/server/http/page/{0}.mask'
	
	index:
		template: index
		master: default
	
pages:
	# Page urls
	# Default page path is /server/http/page/index/index.mask
	# Each page item also has some additional infos
	# - title - Page Title
	
	!/:
		id: index
		template: tasks
		title: Tasks
		env:
			both:
				view:
					- tasks
	/tasks:
		id: tasks
		template: tasks
		title: Tasks
		env:
			both:
				view:
					- tasks
					
	/active:
		id: active
		template: active
		title: Active
	
	/workers:
		id: workers
		template: workers
		title: Workers
		env:
			both:
				view:
					- workers

