# Generic root Configuration
# Some projects contain project-level Configuration

host: 'http://127.0.0.1'

port:
	'#if TEST': 5887
	'default': 5777

mongo:
	db:
		'#if TEST': test-task-scheduler
		'default': task-scheduler